# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=3, verbose_name='Код валюты')),
                ('active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name_plural': 'Вылюты',
                'verbose_name': 'Валюта',
            },
        ),
    ]
