# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 20:36
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_condition',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Условие поставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='re_count',
            field=models.BooleanField(default=True, verbose_name='Пересчитывать в грн?'),
        ),
    ]
