# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
