# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171117_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_title', models.CharField(max_length=10, verbose_name='Короткое обозначение')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-code',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Unit', verbose_name='Единица измерения'),
        ),
    ]
