# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 14:25
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=catalog.models.set_code, max_length=20, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
