# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['weight'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='photo',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
